// Province display mapping utility
export const getProvinceDisplayName = (value) => {
  const provinceMap = {
    'Hanoi': 'Ha Noi',
    'HoChiMinhCity': 'Ho Chi Minh City',
    'HaiPhong': 'Hai Phong',
    'DaNang': 'Da Nang',
    'CanTho': 'Can Tho',
    'BinhDuong': 'Binh Duong',
    'DongNai': 'Dong Nai',
    'HaiDuong': 'Hai Duong',
    'ThanhHoa': 'Thanh Hoa',
    'NgheAn': 'Nghe An',
    'ThuaThienHue': 'Thua Thien Hue',
    'QuangNinh': 'Quang Ninh',
    'BacNinh': 'Bac Ninh',
    'QuangNam': 'Quang Nam',
    'LamDong': 'Lam Dong',
    'NamDinh': 'Nam Dinh',
    'ThaiBinh': 'Thai Binh',
    'PhuTho': 'Phu Tho',
    'BacGiang': 'Bac Giang',
    'HungYen': 'Hung Yen',
    'HaNam': 'Ha Nam',
    'VinhPhuc': 'Vinh Phuc',
    'NinhBinh': 'Ninh Binh',
    'QuangBinh': 'Quang Binh',
    'QuangTri': 'Quang Tri',
    'BinhDinh': 'Binh Dinh',
    'BinhThuan': 'Binh Thuan',
    'KhanhHoa': 'Khanh Hoa',
    'BaRiaVungTau': 'Ba Ria - Vung Tau',
    'LongAn': 'Long An',
    'KienGiang': 'Kien Giang',
    'DakLak': 'Dak Lak',
    'CaMau': 'Ca Mau',
    'BinhPhuoc': 'Binh Phuoc',
    'BacKan': 'Bac Kan',
    'LaoCai': 'Lao Cai',
    'LangSon': 'Lang Son',
    'TuyenQuang': 'Tuyen Quang',
    'YenBai': 'Yen Bai',
    'DienBien': 'Dien Bien',
    'SonLa': 'Son La',
    'HoaBinh': 'Hoa Binh',
    'LaiChau': 'Lai Chau',
    'HaGiang': 'Ha Giang',
    'CaoBang': 'Cao Bang',
    'KonTum': 'Kon Tum',
    'GiaLai': 'Gia Lai',
    'DakNong': 'Dak Nong',
    'SocTrang': 'Soc Trang',
    'TraVinh': 'Tra Vinh',
    'BenTre': 'Ben Tre',
    'VinhLong': 'Vinh Long',
    'AnGiang': 'An Giang',
    'TienGiang': 'Tien Giang',
    'HauGiang': 'Hau Giang',
    'NinhThuan': 'Ninh Thuan',
    'PhuYen': 'Phu Yen',
    'QuangNgai': 'Quang Ngai',
    'BacLieu': 'Bac Lieu'
  };

  return provinceMap[value] || value;
};

export const provinces = [
  { value: 'Hanoi', display: 'Ha Noi' },
  { value: 'HoChiMinhCity', display: 'Ho Chi Minh City' },
  { value: 'HaiPhong', display: 'Hai Phong' },
  { value: 'DaNang', display: 'Da Nang' },
  { value: 'CanTho', display: 'Can Tho' },
  { value: 'BinhDuong', display: 'Binh Duong' },
  { value: 'DongNai', display: 'Dong Nai' },
  { value: 'HaiDuong', display: 'Hai Duong' },
  { value: 'ThanhHoa', display: 'Thanh Hoa' },
  { value: 'NgheAn', display: 'Nghe An' },
  { value: 'ThuaThienHue', display: 'Thua Thien Hue' },
  { value: 'QuangNinh', display: 'Quang Ninh' },
  { value: 'BacNinh', display: 'Bac Ninh' },
  { value: 'QuangNam', display: 'Quang Nam' },
  { value: 'LamDong', display: 'Lam Dong' },
  { value: 'NamDinh', display: 'Nam Dinh' },
  { value: 'ThaiBinh', display: 'Thai Binh' },
  { value: 'PhuTho', display: 'Phu Tho' },
  { value: 'BacGiang', display: 'Bac Giang' },
  { value: 'HungYen', display: 'Hung Yen' },
  { value: 'HaNam', display: 'Ha Nam' },
  { value: 'VinhPhuc', display: 'Vinh Phuc' },
  { value: 'NinhBinh', display: 'Ninh Binh' },
  { value: 'QuangBinh', display: 'Quang Binh' },
  { value: 'QuangTri', display: 'Quang Tri' },
  { value: 'BinhDinh', display: 'Binh Dinh' },
  { value: 'BinhThuan', display: 'Binh Thuan' },
  { value: 'KhanhHoa', display: 'Khanh Hoa' },
  { value: 'BaRiaVungTau', display: 'Ba Ria - Vung Tau' },
  { value: 'LongAn', display: 'Long An' },
  { value: 'KienGiang', display: 'Kien Giang' },
  { value: 'DakLak', display: 'Dak Lak' },
  { value: 'CaMau', display: 'Ca Mau' },
  { value: 'BinhPhuoc', display: 'Binh Phuoc' },
  { value: 'BacKan', display: 'Bac Kan' },
  { value: 'LaoCai', display: 'Lao Cai' },
  { value: 'LangSon', display: 'Lang Son' },
  { value: 'TuyenQuang', display: 'Tuyen Quang' },
  { value: 'YenBai', display: 'Yen Bai' },
  { value: 'DienBien', display: 'Dien Bien' },
  { value: 'SonLa', display: 'Son La' },
  { value: 'HoaBinh', display: 'Hoa Binh' },
  { value: 'LaiChau', display: 'Lai Chau' },
  { value: 'HaGiang', display: 'Ha Giang' },
  { value: 'CaoBang', display: 'Cao Bang' },
  { value: 'KonTum', display: 'Kon Tum' },
  { value: 'GiaLai', display: 'Gia Lai' },
  { value: 'DakNong', display: 'Dak Nong' },
  { value: 'SocTrang', display: 'Soc Trang' },
  { value: 'TraVinh', display: 'Tra Vinh' },
  { value: 'BenTre', display: 'Ben Tre' },
  { value: 'VinhLong', display: 'Vinh Long' },
  { value: 'AnGiang', display: 'An Giang' },
  { value: 'TienGiang', display: 'Tien Giang' },
  { value: 'HauGiang', display: 'Hau Giang' },
  { value: 'NinhThuan', display: 'Ninh Thuan' },
  { value: 'PhuYen', display: 'Phu Yen' },
  { value: 'QuangNgai', display: 'Quang Ngai' },
  { value: 'BacLieu', display: 'Bac Lieu' }
]; 
